default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rominecavalcante
  password: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: pokemon_development

test:
  <<: *default
  database: pokemon_test

production:
  <<: *default
  database: pokemon_production
